-- EuroProcure Intelligence - Snowflake Setup
-- Run once as ACCOUNTADMIN before starting the project

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS EUROPROCURE_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS EUROPROCURE_DB;

CREATE SCHEMA IF NOT EXISTS EUROPROCURE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS EUROPROCURE_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS EUROPROCURE_DB.MARTS;

CREATE ROLE IF NOT EXISTS DBT_ROLE;

GRANT USAGE ON WAREHOUSE EUROPROCURE_WH TO ROLE DBT_ROLE;
GRANT USAGE ON DATABASE EUROPROCURE_DB TO ROLE DBT_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE EUROPROCURE_DB TO ROLE DBT_ROLE;
GRANT CREATE TABLE ON SCHEMA EUROPROCURE_DB.RAW TO ROLE DBT_ROLE;
GRANT CREATE TABLE ON SCHEMA EUROPROCURE_DB.STAGING TO ROLE DBT_ROLE;
GRANT CREATE TABLE ON SCHEMA EUROPROCURE_DB.MARTS TO ROLE DBT_ROLE;
GRANT CREATE VIEW ON SCHEMA EUROPROCURE_DB.STAGING TO ROLE DBT_ROLE;
GRANT CREATE VIEW ON SCHEMA EUROPROCURE_DB.MARTS TO ROLE DBT_ROLE;

GRANT ROLE DBT_ROLE TO USER AHMEDALI58;
